server:
  port: 9527
  info: prov
spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 开启从注册中心动态注册路由的功能，利用服务名进行路由
      # 配置路由
      routes:
        - id: payment_routh           # 路由ID，要求唯一。无固定规则，建议配合服务名
#          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   # 利用服务名路由
          predicates:
            - Path=/payment/get/**    # 断言，路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
#            - After=2021-10-29T19:50:16.938+08:00[Asia/Shanghai]    # 指定时间后才能正常访问
#            - Before
#            - Cookie=username, hkyang    # Cookie Route Predicate需要两个参数，一个是 Cookie name ,一个是正则表达式。
#            - Header=X-Request-Id, \d+   # 两个参数：一个是属性名称和一个正则表达式，这个属性值和正则表达式匹配则执行
#            - Host=**.hkyang.com, **.hkyang.cn  #Host Route Predicate 接收一组参数，一组匹配的域名列表，这个模板是一个 ant 分隔的模板，用.号作为分隔符。 它通过参数中的主机地址作为匹配规则。
#            - Method=GET                  # 请求方式
#            - Path
#            - Query=username, \d+         # 支持传入两个参数，一个是属性名，一个为属性值，属性值可以是正则表达式。




eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
